<!doctype html>
<html lang="id">
<head>
    <meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}"><meta name="theme-color" content="#f5f7f5">
    <link rel="icon" type="image/svg+xml" href="{{ asset('jobagent-mark.svg') }}"><link rel="stylesheet" href="{{ asset('css/app.css') }}"><link rel="stylesheet" href="{{ asset('css/effects.css') }}">
    <title>Dashboard Admin — JobAgent</title>
</head>
<body class="dashboard-page">
    <aside class="admin-sidebar"><a class="brand" href="/"><img src="{{ asset('jobagent-mark.svg') }}" alt=""><span>jobagent<span class="brand-dot">.</span></span></a><div class="sidebar-label">WORKSPACE</div><a class="sidebar-link sidebar-active" href="{{ route('admin.dashboard') }}">▦ <span>Dashboard</span></a><a class="sidebar-link" href="#users">♧ <span>Manajemen pengguna</span></a><a class="sidebar-link" href="/#lowongan">▣ <span>Lowongan kerja</span></a><div class="sidebar-label sidebar-bottom-label">SYSTEM</div><button class="sidebar-link" data-admin-health>◉ <span>Status sistem</span></button><a class="sidebar-link" href="/">↗ <span>Lihat situs</span></a><div class="sidebar-admin"><div class="admin-avatar">{{ mb_substr($admin->name, 0, 1) }}</div><div><strong>{{ $admin->name }}</strong><span>Administrator</span></div><button data-admin-logout title="Keluar">↗</button></div></aside>
    <main class="admin-main">
        <header class="admin-topbar"><div><span class="section-kicker">WORKSPACE / OVERVIEW</span><h1>Dashboard</h1></div><div class="admin-top-actions"><span class="admin-date">{{ now()->translatedFormat('l, d F Y') }}</span><a class="admin-avatar-link" href="{{ route('admin.dashboard') }}">{{ mb_substr($admin->name, 0, 1) }}</a><button class="admin-logout-button" data-admin-logout>Keluar</button></div></header>
        <section class="admin-welcome"><div><span class="admin-welcome-kicker">JOBAGENT CONTROL CENTER</span><h2>Selamat bekerja, {{ $admin->name }}.</h2><p>Pantau komunitas dan kelola akun JobAgent dalam satu tempat.</p></div><div class="welcome-orb">✳</div></section>
        <section class="stat-grid">
            <article class="stat-card"><span>Total pengguna</span><strong>{{ number_format($stats['users']) }}</strong><small>Semua akun terdaftar</small><i>♧</i></article>
            <article class="stat-card"><span>Pencari kerja</span><strong>{{ number_format($stats['candidates']) }}</strong><small>Talenta di JobAgent</small><i>⌕</i></article>
            <article class="stat-card"><span>Perusahaan</span><strong>{{ number_format($stats['employers']) }}</strong><small>Tim perekrut aktif</small><i>▣</i></article>
            <article class="stat-card"><span>Lowongan aktif</span><strong>{{ number_format($stats['jobs']) }}</strong><small>{{ number_format($stats['applications']) }} lamaran terkirim</small><i>↗</i></article>
        </section>
        <section class="admin-panel" id="users">
            <div class="panel-heading"><div><span class="section-kicker">DIRECTORY</span><h2>Manajemen pengguna</h2><p>Lihat, tambah, perbarui, atau hapus akun terdaftar.</p></div><button class="button" data-add-user>＋ Tambah akun</button></div>
            <form class="user-search" method="get" action="{{ route('admin.dashboard') }}"><span>⌕</span><input name="q" value="{{ $search }}" placeholder="Cari nama, email, perusahaan..."><button class="button button-small">Cari</button></form>
            <div class="table-scroll"><table class="user-table"><thead><tr><th>PENGGUNA</th><th>JENIS AKUN</th><th>DETAIL</th><th>VERIFIKASI</th><th>TERDAFTAR</th><th></th></tr></thead><tbody>
            @forelse($users as $user)
                <tr>
                    <td><div class="table-person"><span class="table-avatar">@if($user->role === 'employer' && $user->company_logo_path)<img src="{{ \Illuminate\Support\Facades\Storage::disk('public')->url($user->company_logo_path) }}" alt="" loading="lazy">@elseif($user->avatar_path)<img src="{{ \Illuminate\Support\Facades\Storage::disk('public')->url($user->avatar_path) }}" alt="" loading="lazy">@else{{ mb_substr($user->name, 0, 1) }}@endif</span><span><strong>{{ $user->name }}</strong><small>{{ $user->email }}</small></span></div></td>
                    <td><span class="role-badge role-{{ $user->role }}">{{ ['candidate'=>'Pencari kerja','employer'=>'Perusahaan','admin'=>'Admin'][$user->role] ?? $user->role }}</span></td>
                    <td class="user-detail">{{ $user->role === 'employer' ? ($user->company_name ?: '—') : ($user->location ?: '—') }}<small>{{ $user->phone ?: $user->industry ?: $user->headline ?: 'Profil belum dilengkapi' }}</small></td>
                    <td><span class="verify-badge {{ $user->email_verified_at ? 'verified-state' : 'pending-state' }}">{{ $user->email_verified_at ? 'Terverifikasi' : 'Menunggu verifikasi email' }}</span></td>
                    <td class="date-cell">{{ $user->created_at->format('d M Y') }}</td>
                    <td class="table-actions">@if($user->role !== 'admin')<button data-edit-user="{{ $user->id }}" data-user="{{ json_encode(['id'=>$user->id,'name'=>$user->name,'email'=>$user->email,'role'=>$user->role,'phone'=>$user->phone,'location'=>$user->location,'headline'=>$user->headline,'company_name'=>$user->company_name,'industry'=>$user->industry,'company_size'=>$user->company_size,'website'=>$user->website], JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_AMP | JSON_HEX_QUOT) }}" aria-label="Edit akun">✎</button><button class="delete-action" data-delete-user="{{ $user->id }}" data-user-name="{{ $user->name }}" aria-label="Hapus akun">×</button>@else<span class="protected-mark" title="Akun admin dilindungi">⌑</span>@endif</td>
                </tr>
            @empty<tr><td colspan="6" class="empty-table">Belum ada pengguna untuk ditampilkan.</td></tr>@endforelse
            </tbody></table></div>
            <div class="pagination-wrap">{{ $users->links() }}</div>
        </section>
        <section class="admin-panel activity-panel"><div class="panel-heading"><div><span class="section-kicker">AUDIT TRAIL</span><h2>Aktivitas admin terbaru</h2><p>Riwayat perubahan akun tercatat untuk akuntabilitas.</p></div><span class="audit-lock">⌑ Privat</span></div><div class="audit-list">@forelse($activity as $entry)<div class="audit-entry"><span class="audit-action">{{ $entry->action === 'user.created' ? '+' : ($entry->action === 'user.deleted' ? '−' : '✎') }}</span><span><strong>{{ $entry->action === 'user.created' ? 'Akun dibuat' : ($entry->action === 'user.deleted' ? 'Akun dihapus' : 'Akun diperbarui') }}</strong><small>{{ $entry->target_email }}@if($entry->metadata['fields'] ?? false) · {{ implode(', ', $entry->metadata['fields']) }}@endif</small></span><time>{{ $entry->created_at->diffForHumans() }}</time></div>@empty<div class="audit-empty">Belum ada perubahan akun yang dilakukan.</div>@endforelse</div></section>
        <footer class="admin-footer"><span>JobAgent Admin Workspace · Akses terbatas</span><button data-admin-health>Periksa status sistem</button></footer>
    </main>
    <div class="modal-backdrop" id="user-modal" hidden><section class="auth-modal admin-user-modal" role="dialog" aria-modal="true" aria-labelledby="user-modal-title"><button class="modal-close" aria-label="Tutup" data-close>×</button><div class="auth-heading"><span class="section-kicker">USER MANAGEMENT</span><h2 id="user-modal-title">Tambah akun.</h2><p id="user-modal-description">Pengguna dapat masuk setelah membuat akun dan memverifikasi email lewat tautan yang dikirim ke email mereka.</p></div><form class="auth-form" id="user-form"><input type="hidden" name="id"><label>Nama lengkap<input name="name" required minlength="2" maxlength="100"></label><label>Email<input name="email" required type="email" maxlength="254"></label><label>Jenis akun<select name="role"><option value="candidate">Pencari kerja</option><option value="employer">Perusahaan</option></select></label><div class="form-row"><label>Telepon<input name="phone" maxlength="30"></label><label>Lokasi<input name="location" maxlength="100" data-autocomplete="location" autocomplete="off"></label></div><label>Bidang / headline<input name="headline" maxlength="120" data-autocomplete="headline" autocomplete="off"></label><label>Nama perusahaan<input name="company_name" maxlength="120"></label><div class="form-row"><label>Industri<input name="industry" maxlength="100"></label><label>Ukuran tim<input name="company_size" maxlength="40"></label></div><label>Situs perusahaan<input name="website" type="url" maxlength="200"></label><p class="form-error" id="user-form-error" hidden></p><button type="submit" class="button auth-submit">Simpan akun <span>→</span></button></form></section></div>
    <div class="modal-backdrop" id="admin-health-modal" hidden><section class="auth-modal status-modal" role="dialog" aria-modal="true"><button class="modal-close" aria-label="Tutup" data-close>×</button><div class="auth-heading"><span class="section-kicker">JOBAGENT CHECKUP</span><h2>Status layanan.</h2><p>Pemeriksaan koneksi aplikasi, database, dan sistem akun.</p></div><div class="diagnostic-list"><div><span class="diagnostic-dot"></span><strong>Database</strong><span data-admin-check="database">Memeriksa...</span></div><div><span class="diagnostic-dot"></span><strong>Sistem akun</strong><span data-admin-check="firebase">Memeriksa...</span></div><div><span class="diagnostic-dot"></span><strong>Email & Google sign-in</strong><span data-admin-check="email">Memeriksa...</span></div></div><button class="button auth-submit" data-admin-health>Periksa ulang <span>↻</span></button><p class="diagnostic-checked" id="admin-health-time"></p></section></div>
    <div class="toast" id="toast" hidden><span class="toast-check">✓</span><span id="toast-message"></span></div>
    <script>window.JobAgent = {config: @json($firebaseConfig)};</script>
    <script src="{{ asset('js/smart-fields.js') }}" defer></script>
    <script src="{{ asset('js/admin.js') }}" defer></script>
</body>
</html>
